# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ViroSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ViroSample

  target 'ViroSample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNSound', :path => '../node_modules/react-native-sound'

    pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

  end

  target 'ViroSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ViroSample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ViroSample-tvOS

  target 'ViroSample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
